### ISSUE TITLE
Track error when logged out

### ISSUE THREAD

**Issue by sjcallender** [shoeshine/klaviyoconnect#1]
Upon trying to add an item to the cart, I get this error message: "You must identify a user by email or ID."

screenshot: https://ssdd.d.pr/Q3gHpF

**Comment by johnnynotsolucky** [comment]
@sjcallender Are you a guest user when this happens?

**Comment by sjcallender** [comment]
@johnnynotsolucky Yes, but it happens when I'm logged in too.

**Comment by johnnynotsolucky** [comment]
Cool. It's probably because `onSaveOrder` assumes the email field is already set:

```
$customerProperties = ['$email' => $order->email];
```

This wouldn't be the case for a new cart. 

When I tested it I think I had a cart which had already been created and the `email` field was populated from a previous checkout which I didn't complete.

**Comment by daniellelecomte** [comment]
Hey y'all - I am seeing this error on a Craft 4 site:
Craft 4.8.0, Commerce 4.5.4, Klaviyo 5.0.8, PHP 8.2

When I try to finish checkout as a guest, I am greeted with "You must identify a user by email or ID."

Screenshot: https://d.pr/i/hhYCYr

Works just fine when a user is logged in!

We're basically just capturing the subscriber when they place an order. 

```
<form method="post" action="">
    {{ csrfInput() }}
    {{ redirectInput('/checkout/order?number={number}') }}
    {{ hiddenInput('cancelUrl', '/checkout/payment'|hash) }}
    {{ hiddenInput('orderEmail', cart.email) }}

    {# Klaviyo fields #}
    {{ hiddenInput('action', '/klaviyoconnect/api/track') }}
    {{ hiddenInput('confirmOptIn', '0') }}
    {{ hiddenInput('forward', '/commerce/payments/pay') }}

    <div class="mt-4">
        {% namespace cart.gateway.handle|commercePaymentFormNamespace %}
            {{ cart.gateway.getPaymentFormHtml({})|raw }}
        {% endnamespace %}
    </div>

    <div class="py-4">
        <label class="text-lg-2">
            {{ hiddenInput('list', null) }}
            <input type="checkbox" id="subscribe" name="list" value="{{ klaviyo.klaviyoList.id ?? '' }}" checked />
            Subscribe to our newsletter
        </label>
    </div>

    {% include '_components/shared/recaptcha' with { action: 'checkout' } %}

    <button class="btn mt-4 g-recaptcha" data-sitekey="{{ getenv('RECAPTCHA_SITE_KEY') }}" type="submit">Place Order</button>
</form>
```

Any insight? Thanks!
